apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  # The Sidecar is defined under initContainers with a RestartPolicy
  initContainers:
    - name: sidecar-container
      image: ubuntu:latest
      restartPolicy: Always #This is important part
      command: ["sh", "-c", "while true; do cat /var/log/nginx/access.log /var/log/nginx/error.log; sleep 30; done"]
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/nginx

  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/nginx

  volumes:
    - name: shared-logs
      emptyDir: {}
